package org.cdlib.xtf.textIndexer;


/**
 * Copyright (c) 2004, Regents of the University of California
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * - Neither the name of the University of California nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;
import javax.xml.transform.Templates;
import javax.xml.transform.Transformer;
import javax.xml.transform.sax.SAXSource;

import net.sf.saxon.om.NodeInfo;
import net.sf.saxon.tree.TreeBuilder;
import net.sf.saxon.value.StringValue;

import org.apache.lucene.util.StringUtil;
import org.cdlib.xtf.cache.Dependency;
import org.cdlib.xtf.cache.FileDependency;
import org.cdlib.xtf.servletBase.StylesheetCache;
import org.cdlib.xtf.textEngine.IndexUtil;
import org.cdlib.xtf.util.Attrib;
import org.cdlib.xtf.util.EasyNode;
import org.cdlib.xtf.util.Path;
import org.cdlib.xtf.util.SubDirFilter;
import org.cdlib.xtf.util.Trace;
import org.cdlib.xtf.util.XMLWriter;
import org.xml.sax.InputSource;

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

/**
 * This class is the main processing shell for files in the source text
 * tree. It optimizes Lucene database access by opening the index once at
 * the beginning, processing all the source files in the source tree
 * (including skipping non-source XML files in the tree), and closing the
 * database at the end. <br><br>
 *
 * Internally, this class uses the {@link org.cdlib.xtf.textIndexer.XMLTextProcessor}
 * class to actually split the source files up into chunks and add them to the
 * Lucene index.
 *
 */
public class SrcTreeProcessor 
{

  private static final FileFilter dcFileFilter = pathname -> pathname.isFile() && pathname.getName().endsWith(".dc.xml");


  private static final FileFilter subDirFileFilter = pathname -> pathname.isDirectory();

  private final IndexerConfig cfgInfo;
  // Instantiate a text processor object to use on each XML file
  // encountered in the file tree.
  //
  private final XMLTextProcessor textProcessor;
  private final StylesheetCache stylesheetCache = new StylesheetCache(100, 0, true);
  private final Templates docSelector;

  private final StringBuffer docBuf = new StringBuffer(1024);
  private final StringBuffer dirBuf = new StringBuffer(1024);
  private final String docSelPath;
  private File docSelCacheFile;
  private final DocSelCache docSelCache = new DocSelCache();

  private final Templates[] preFilters;
    /** Indexing open function. <br><br>
     *
     *  Calls the {@link org.cdlib.xtf.textIndexer.XMLTextProcessor}
     *  {@link org.cdlib.xtf.textIndexer.XMLTextProcessor#open(String, IndexInfo, boolean, boolean) open()}
     *  method to actually create/open the Lucene index.
     *
     *  @param cfgInfo   The {@link org.cdlib.xtf.textIndexer.IndexerConfig IndexerConfig}
     *                   that indentifies the Lucene index, source text tree, and
     *                   other parameters required to perform indexing. <br><br>
     *
     *  @throws IOException  Any I/O exceptions generated by the
     *                       {@link org.cdlib.xtf.textIndexer.XMLTextProcessor}
     *                       {@link org.cdlib.xtf.textIndexer.XMLTextProcessor#open(String, IndexInfo, boolean, boolean) open()}
     *                       method. <br><br>
     */
  public SrcTreeProcessor(IndexerConfig cfgInfo,List<String> tokenizedFields) throws Exception {
      // Hang on to a reference to the config info.
      this.cfgInfo = cfgInfo;
      assert this.cfgInfo != null;
      this.textProcessor = new XMLTextProcessor(tokenizedFields);

      // If no XTF home directory specified, assume it is the same
      // directory as the config file.
      //
      if (cfgInfo.xtfHomePath == null) {
        cfgInfo.xtfHomePath = new File(cfgInfo.cfgFilePath).getParentFile()
                              .toString();
      }

      // Make a transformer for the docSelector stylesheet.
      docSelPath = Path.resolveRelOrAbs(cfgInfo.xtfHomePath,
                                        cfgInfo.indexInfo.docSelectorPath);
      docSelector = stylesheetCache.find(docSelPath);

      // Load the previous docSelector cache (if any)
      loadCache(cfgInfo);

      // Open the Lucene index specified by the config info.
      //if (!cfgInfo.prefilterOnly) {
        textProcessor.open(cfgInfo.xtfHomePath, cfgInfo.indexInfo, cfgInfo.clean,
            cfgInfo.force);
      //}
      cfgInfo.clean = false;
      this.preFilters = new Templates[] { stylesheetCache.find(Path.resolveRelOrAbs(cfgInfo.xtfHomePath, "style/textIndexer/dcPreFilter.xsl")) };
      assert this.preFilters[0] != null;
  }
    // open()

    ////////////////////////////////////////////////////////////////////////////

  /** Indexing close function. <br><br>
   *
   *  Calls the {@link org.cdlib.xtf.textIndexer.XMLTextProcessor}
   *  {@link org.cdlib.xtf.textIndexer.XMLTextProcessor#processQueuedTexts() processQueuedTexts()}
   *  method to flush all the pending Lucene writes to disk. Then it calls the
   *  {@link org.cdlib.xtf.textIndexer.XMLTextProcessor}
   *  {@link org.cdlib.xtf.textIndexer.XMLTextProcessor#close() close()}
   *  method to actually close the Lucene index. <br><br>
   *
   *  @throws IOException  Any I/O exceptions generated by the
   *                       {@link org.cdlib.xtf.textIndexer.XMLTextProcessor}
   *                       {@link org.cdlib.xtf.textIndexer.XMLTextProcessor#close() close()}
   *                       method. <br><br>
   *
   */
  public void close()
          throws IOException, InterruptedException {
    // Flush the remaining open documents.
    if (!cfgInfo.prefilterOnly)
      textProcessor.processQueuedTexts();

    // Save the doc selector cache. We do this *after* processing the texts,
    // in case something catastrophic happens in there.
    //
    saveCache();



    // Close the index database.
    textProcessor.close();
  } // close()

  ////////////////////////////////////////////////////////////////////////////

  String calcIndexPath()
  {
    String indexPath = Path.resolveRelOrAbs(cfgInfo.xtfHomePath,
        cfgInfo.indexInfo.indexPath);
    return Path.normalizePath(indexPath);
  }

  ////////////////////////////////////////////////////////////////////////////

  /** Load the previous docSelector cache.
   *
   *  @param cfgInfo   The {@link org.cdlib.xtf.textIndexer.IndexerConfig IndexerConfig}
   *                   that indentifies the Lucene index, source text tree, and
   *                   other parameters required to perform indexing. <br><br>
   */
  public void loadCache(IndexerConfig cfgInfo) 
  {
    docSelCache.clear();

    // Figure out the path to the cache file
    docSelCacheFile = new File(calcIndexPath() + "docSelect.cache");

    // Calculate all the file dependencies of the docSelector stylesheet.
    StringBuilder depBuf = new StringBuilder();
    for (Iterator<Dependency> it = stylesheetCache.getDependencies(docSelPath); it.hasNext(); ) {
      Dependency d = it.next();
      if (d instanceof FileDependency) {
        depBuf.append(d);
        depBuf.append("\n");
      }
    }
    docSelCache.dependencies = depBuf.toString();

    // If we're making a clean index, delete the old cache file.
    if (cfgInfo.clean) {
      docSelCacheFile.delete();
      return;
    }

    // If the cache file doesn't exist, don't load it.
    if (!docSelCacheFile.canRead())
      return;

    // Read the file.
    String thisDep = docSelCache.dependencies;
    try {
      docSelCache.load(docSelCacheFile);
    }
    catch (IOException e) {
      Trace.warning(
          "Warning: Error loading docSelector cache \"" + docSelCacheFile +
          "\": " + e);
      docSelCache.clear();
      return;
    }
    
    // If the dependencies are different, toss it.
    if (!docSelCache.dependencies.equals(thisDep)) {
      Trace.debug(
        "Note: docSelector stylesheet or sub-sheet " +
        " has changed... throwing away " + "old docSelector cache.");
      docSelCacheFile.delete();
      docSelCache.clear();
      docSelCache.dependencies = thisDep;
    }
  } // loadCache()

  ////////////////////////////////////////////////////////////////////////////

  /** Save the docSelector cache.
   */
  public void saveCache() 
  {
    try {
      docSelCache.save(docSelCacheFile);
    }
    catch (IOException e) {
      Trace.warning(
        "Warning: Error writing docSelector cache \"" + docSelCacheFile + "\": " + e);
    }
  } // saveCache()

  private long count =  0L;
  ////////////////////////////////////////////////////////////////////////////



  /** Process a directory containing source XML files. <br><br>
   *
   * This method iterates through a source directory's contents indexing any
   * valid files it finds, any processing any sub-directories. <br><br>
   *
   * @param curDir        The current directory to be processed. <br>
   * @param subDirFilter  Sub-dirs to scan, or null for all. <br>
   * @param topLevel      true for the top-level directory, false else. <br>     
   *
   *  @throws   Exception  Any exceptions generated internally
   *                       by the <code>File</code> class or the
   *                       {@link org.cdlib.xtf.textIndexer.XMLTextProcessor}
   *                       class. <br><br>
   *
   */

  public void processDir(final File curDir, SubDirFilter subDirFilter, boolean topLevel)
    throws Exception 
  {
      if(curDir == null) return;
      count = count + 1;
      if (/*count < 4440 &&*/ (count % 100) == 0) {
          System.err.println();
          System.err.print(String.format("%012d",count) + ": ");
      } /*else if (count >= 4479) {
          System.err.println(String.format("%012d",count) + ": " + curDir);
      } */
      System.err.print('.');
      System.err.flush();
    // If we're only doing a subset and this directory isn't in it, skip.
    /* if (subDirFilter != null && !subDirFilter.approve(curDir))
      return; */

    File[] files;
    try {
        files = curDir.listFiles(dcFileFilter);
    } catch (Throwable throwable) {
        throwable.printStackTrace();
        System.exit(10);
        return;
    }

    if (files == null) {
      Trace.warning(
        "Warning: error retrieving file list for directory: " + curDir);
      return;
    }


    // Process all of the non-directory files first. Form a document 
    // representing the directory and all its files.
    //
    //docBuf.setLength(0);
    //dirBuf.setLength(0);

    //String dirPath = Path.normalizePath(curDir.toString());
    //docBuf.append("<directory dirPath=\"").append(StringUtil.escapeHTMLChars(dirPath)).append("\">\n");
    int nFiles = 0;
    for (File f : files) {
        processFile(f, preFilters);
        ++nFiles;
    }

    String dirKey;
    if (topLevel)
      dirKey = cfgInfo.indexInfo.indexName + ":/";
    else
      dirKey = IndexUtil.calcDocKey(new File(cfgInfo.xtfHomePath),
                                    cfgInfo.indexInfo, curDir);
    
    // In the old mode (scanAllDirs = false), if we found any files to process,
    // the convention is that subdirectories contain file related to the ones 
    // we processed, and that they shouldn't be processed individually.
    //
    // In the new mode (scanAllDirs = true), we always process subdirs. This
    // seems to be what most people really want and expect.
    //
    if (nFiles > 0 && !cfgInfo.indexInfo.scanAllDirs)
      return;

    // Recursively try sub-directories.
    File[] subDirs = curDir.listFiles(subDirFileFilter);
    if(subDirs != null) {
        for (File f : subDirs) {
            processDir(f, subDirFilter, false);
        }
    }
  } // processDir()

  public void finishInput() throws InterruptedException {
      textProcessor.queueText(null,false);
  }

  ////////////////////////////////////////////////////////////////////////////

  /** Process file. <br><br>
   *
   * This method processes a source file, including source text XML files,
   * PDF files, etc. <br><br>
   *
   * @param parentEl       DOM element representing the current file to be
   *                       processed. This may be a source XML file, PDF file,
   *                       etc. <br><br>
   *
   * @return               true if the document was processed, false if it was
   *                       skipped due to skipping rules.<br><br>
   *
   * @throws   Exception   Any exceptions generated internally by the <code>File</code>
   *                       class or the {@link org.cdlib.xtf.textIndexer.XMLTextProcessor}
   *                       class. <br><br>
   *
   */
  public boolean processFile(String dir, EasyNode parentEl)
    throws Exception {
      // Gather all the info from the element's attributes.
      File srcPath = null;
      Vector<Templates> preFilterVec = new Vector<>();
      String format = null;

      for (int i = 0; i < parentEl.nAttrs(); i++) {
          String attrName = parentEl.attrName(i);
          String attrVal = parentEl.attrValue(i);

          // Get the file name and check it.
          if (attrName.equalsIgnoreCase("fileName")) {
              srcPath = new File(Path.normalizeFileName(dir + attrVal));
              if (!srcPath.canRead()) {
                  Trace.error("Error: cannot read input document '" + srcPath + "'");
                  return false;
              }
          }

          // Is there an input filter(s) specified?
          else if (attrName.equalsIgnoreCase("preFilter")) {
              // Break up a list separated by semicolons or commas.
              StringTokenizer st = new StringTokenizer(attrVal, ";,");
              while (st.hasMoreTokens()) {
                  String partialPath = st.nextToken();
                  String preFilterPath = Path.resolveRelOrAbs(cfgInfo.xtfHomePath,
                          partialPath);
                  preFilterVec.add(stylesheetCache.find(preFilterPath));
              } // while
          } // else

          // Is there a format specified?
          else if (attrName.equalsIgnoreCase("type")) {
              format = attrVal;
              if (format.equalsIgnoreCase("XML"))
                  format = "XML";
              else if (format.equalsIgnoreCase("PDF"))
                  format = "PDF";
              else if (format.equalsIgnoreCase("HTML"))
                  format = "HTML";
              else if (format.equalsIgnoreCase("DOC") || format.equalsIgnoreCase("MSWord"))
                  format = "MSWord";
              else if (format.equalsIgnoreCase("Text"))
                  format = "Text";
              else if (format.equalsIgnoreCase("MARC"))
                  format = "MARC";
              else {
                  Trace.error("Error: docSelector returned unknown type: '" + format +
                          "'");
                  return false;
              }
          }

          // Other attributes are in error.
          else {
              Trace.error(
                      "Error: docSelector returned unknown attribute: '" + attrName + "'");
              return false;
          }
      } // while

      // Make sure the filename was specified.
      if (srcPath == null) {
          Trace.error("Error: docSelector must return 'fileName' attribute");
          return false;
      }

      // If no format was specified, bail out.
      if (format == null) {
          Trace.warning(
                  "Warning: file type not specified for '" +
                          srcPath);
          return false;
      }
      return processFile(srcPath, preFilterVec.toArray(new Templates[0]));
  }
  public boolean processFile(File srcPath,Templates[] preFilters) throws Exception {
    // We need to refer to the file in a way that isn't dependent on the
    // particular location the index is at right now. So calculate a key
    // that just contains the index name and the part of the path after that
    // index's data directory.
    //
    String key = srcPath.getName().replaceAll("\\..*","");/*IndexUtil.calcDocKey(new File(cfgInfo.xtfHomePath),
                                      cfgInfo.indexInfo, srcPath);*/

    // Calculate a proper system ID for this file.
    String systemId = srcPath.toURI().toURL().toString();

    byte[] data = Files.readAllBytes(srcPath.toPath());

    InputSource finalSrc = new InputSource(new ByteArrayInputStream(data));// BufferedInputStream(new FileInputStream()))//= new InputSource(systemId);
    processFile(key,finalSrc,srcPath.lastModified(),srcPath.length(),preFilters);

    // Let the caller know we didn't skip the file.
    return true;
  } // processFile()


    public void processFile(String key, InputSource src, long lastModified, long totalSize, Templates[] preFilters) throws Exception {
        // Now queue up the file.
        textProcessor.checkAndQueueText(new XMLIndexSource(src,
                lastModified,
                totalSize,
                key,
                preFilters,
                null));
    } // processFile()

  ////////////////////////////////////////////////////////////////////////////

} // class SrcTreeProcessor
